[project]
name = "stylegan3-copy"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "click>=8.3.1",
    "glfw>=2.10.0",
    "imageio>=2.37.2",
    "imgui>=2.0.0",
    "matplotlib>=3.10.8",
    "ninja>=1.13.0",
    "numpy>=2.4.2",
    "pillow>=12.1.1",
    "psutil>=7.2.2",
    "pyopengl>=3.1.10",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "setuptools<81",
    "tensorboard>=2.20.0",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "tqdm>=4.67.3",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cu130" }]
torchvision = [{ index = "pytorch-cu130" }]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
